name: Docker build

on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Set up SSH
        uses: MrSquaare/ssh-setup-action@2d028b70b5e397cf8314c6eaea229a6c3e34977a # v3.1.0
        with:
            host: github.com
            private-key: ${{ secrets.PRIVATE_REPO_SSH_KEY }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
            load: true
            file: ./Dockerfile
            ssh: default
            cache-from: type=gha
            cache-to: type=gha,mode=max
